apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.APP_NAME }}-service
  namespace: {{ .Release.NAMESPACE }}
spec:
  selector:
    app: {{ .Release.APP_NAME }}
  ports:
  - port: 80
    targetPort: 8080