apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.APP_NAME }}-db
  namespace: {{ .Release.NAMESPACE }}
spec:
  clusterIP: None
  selector:
    app: { .Release.APP_NAME }}-db
  ports:
  - port: 5432