apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.APP_NAME }}-ingress
  namespace: {{ .Release.NAMESPACE }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/limit-rpm: "60"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Release.APP_DOMAIN }}
    secretName: {{ .Release.APP_NAME }}-tls-secret
  rules:
  - host: {{ .Release.APP_DOMAIN }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.APP_NAME }}-service
            port:
              number: 80