apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.APP_NAME }}-pdb
  namespace: {{ .Release.NAMESPACE }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Release.APP_NAME }}