apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.APP_NAME }}-db-secret
  namespace: {{ .Release.NAMESPACE }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.DB_USER }}"
  DB_PASSWORD: "{{ .Values.DB_PASSWORD }}"
  DB_NAME: "{{ .Values.DB_NAME }}"