apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.DB_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.DB_PASSWORD }}"
  POSTGRES_DB: "{{ .Values.DB_NAME }}"